/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentPackage;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author plumi
 */
public class MainPage extends javax.swing.JFrame {

    ResultSet rs;
    int StdId;

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        addpanel.setVisible(false);
        viewpanel.setVisible(false);
        //EditPanel.setVisible(false);
        viewpanelEditbutton.setVisible(false);
        viewpanelDeletebutton.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        addpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        radiomale = new javax.swing.JRadioButton();
        radiofemale = new javax.swing.JRadioButton();
        txtdob = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        addpanelclose = new javax.swing.JButton();
        addtitle = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        toggleview = new javax.swing.JToggleButton();
        toggleedit = new javax.swing.JToggleButton();
        toggleadd = new javax.swing.JToggleButton();
        btnViewAll = new javax.swing.JToggleButton();
        viewpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        btnfirstpage = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();
        btnlastpage = new javax.swing.JButton();
        viewpanelclose = new javax.swing.JButton();
        viewpanelEditbutton = new javax.swing.JButton();
        addtitle1 = new javax.swing.JLabel();
        studentId = new javax.swing.JLabel();
        viewpanelDeletebutton = new javax.swing.JButton();
        EditPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        EditCloseButton = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        EditTextname = new javax.swing.JTextField();
        EditTextaddress = new javax.swing.JTextField();
        EditTextphone = new javax.swing.JTextField();
        EditTextgender = new javax.swing.JTextField();
        EditTextemail = new javax.swing.JTextField();
        EditTextdob = new javax.swing.JTextField();
        addtitle2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        EditTextlastname = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        addstd = new javax.swing.JMenuItem();
        viewstd = new javax.swing.JMenuItem();
        editstd = new javax.swing.JMenuItem();
        delstd = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dolphin", 0, 14)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Dolphin", 0, 14)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Dolphin", 0, 14)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Dolphin", 0, 14)); // NOI18N
        jLabel5.setText("Phone");

        jLabel6.setFont(new java.awt.Font("Dolphin", 0, 14)); // NOI18N
        jLabel6.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Dolphin", 0, 14)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Dolphin", 0, 14)); // NOI18N
        jLabel8.setText("DOB");

        txtfirstname.setName("txt_firstname"); // NOI18N

        txtemail.setName("txt_email"); // NOI18N

        txtlastname.setName("txt_lastname"); // NOI18N

        txtaddress.setName("txt_address"); // NOI18N

        txtphone.setName("txt_address"); // NOI18N

        gender.add(radiomale);
        radiomale.setFont(new java.awt.Font("Dolphin", 0, 14)); // NOI18N
        radiomale.setText("Male");
        radiomale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiomaleActionPerformed(evt);
            }
        });

        gender.add(radiofemale);
        radiofemale.setFont(new java.awt.Font("Dolphin", 0, 14)); // NOI18N
        radiofemale.setLabel("Female");
        radiofemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiofemaleActionPerformed(evt);
            }
        });

        txtdob.setName("txt_dob"); // NOI18N

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");

        jLabel9.setFont(new java.awt.Font("Dolphin", 0, 14)); // NOI18N
        jLabel9.setText("M/D/Y");

        addpanelclose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addpanelclose.setText("X");
        addpanelclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpanelcloseActionPerformed(evt);
            }
        });

        addtitle.setText("ADD DATA");

        javax.swing.GroupLayout addpanelLayout = new javax.swing.GroupLayout(addpanel);
        addpanel.setLayout(addpanelLayout);
        addpanelLayout.setHorizontalGroup(
            addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addpanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(275, 275, 275))
                    .addGroup(addpanelLayout.createSequentialGroup()
                        .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addpanelLayout.createSequentialGroup()
                                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addtitle, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(4, 4, 4)
                                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addpanelLayout.createSequentialGroup()
                                        .addComponent(radiomale)
                                        .addGap(18, 18, 18)
                                        .addComponent(radiofemale))
                                    .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addpanelclose)
                                        .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(txtphone, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtaddress, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtlastname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtfirstname, javax.swing.GroupLayout.Alignment.LEADING)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addpanelLayout.createSequentialGroup()
                                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addpanelLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btncancel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addpanelLayout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        addpanelLayout.setVerticalGroup(
            addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpanelLayout.createSequentialGroup()
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addpanelclose)
                    .addComponent(addtitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(radiomale)
                    .addComponent(radiofemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsave)
                    .addComponent(btncancel))
                .addGap(320, 320, 320))
        );

        jLabel10.setFont(new java.awt.Font("Dolphin", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Student's Database System");
        jLabel10.setFocusable(false);

        toggleview.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        toggleview.setText("View Data");
        toggleview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleviewActionPerformed(evt);
            }
        });

        toggleedit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        toggleedit.setText("Edit / Delete");
        toggleedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleeditActionPerformed(evt);
            }
        });

        toggleadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        toggleadd.setText("Add Data");
        toggleadd.setToolTipText("");
        toggleadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleaddActionPerformed(evt);
            }
        });

        btnViewAll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toggleadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toggleedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toggleview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toggleadd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toggleview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toggleedit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnViewAll)
                .addContainerGap())
        );

        viewpanel.setToolTipText("Student Details");
        viewpanel.setName("viewpanel"); // NOI18N
        viewpanel.setPreferredSize(new java.awt.Dimension(250, 200));

        jLabel1.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel1.setText("Name");

        jLabel11.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel11.setText("Address");

        jLabel12.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel12.setText("Phone");

        jLabel13.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel13.setText("Gender");

        jLabel14.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel14.setText("Email");

        jLabel15.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel15.setText("DOB");

        lblname.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        lblname.setText(" ");
        lblname.setToolTipText("");

        lblphone.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        lblphone.setText(" ");

        lbladdress.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        lbladdress.setText(" ");

        lblgender.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        lblgender.setText(" ");

        lblemail.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        lblemail.setText(" ");

        lbldob.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        lbldob.setText(" ");

        btnfirstpage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfirstpage.setText("<<");
        btnfirstpage.setName("btnfirstpage"); // NOI18N
        btnfirstpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstpageActionPerformed(evt);
            }
        });

        btnnext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnext.setText(">");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnprevious.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnprevious.setText("<");
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });

        btnlastpage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlastpage.setText(">>");
        btnlastpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastpageActionPerformed(evt);
            }
        });

        viewpanelclose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewpanelclose.setText("X");
        viewpanelclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpanelcloseActionPerformed(evt);
            }
        });

        viewpanelEditbutton.setText("Edit this one");
        viewpanelEditbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpanelEditbuttonActionPerformed(evt);
            }
        });

        addtitle1.setText("VIEW DATA");

        studentId.setText(" ");

        viewpanelDeletebutton.setText("Delete");
        viewpanelDeletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpanelDeletebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewpanelLayout = new javax.swing.GroupLayout(viewpanel);
        viewpanel.setLayout(viewpanelLayout);
        viewpanelLayout.setHorizontalGroup(
            viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewpanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(viewpanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(viewpanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(viewpanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(viewpanelLayout.createSequentialGroup()
                                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldob, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(viewpanelLayout.createSequentialGroup()
                                .addComponent(btnfirstpage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnprevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnnext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnlastpage))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewpanelLayout.createSequentialGroup()
                        .addComponent(addtitle1)
                        .addGap(29, 29, 29)
                        .addComponent(studentId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewpanelclose)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewpanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(viewpanelEditbutton)
                        .addGap(18, 18, 18)
                        .addComponent(viewpanelDeletebutton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        viewpanelLayout.setVerticalGroup(
            viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewpanelLayout.createSequentialGroup()
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpanelclose)
                    .addComponent(addtitle1)
                    .addComponent(studentId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbladdress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblphone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblgender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lbldob))
                .addGap(28, 28, 28)
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfirstpage)
                    .addComponent(btnnext)
                    .addComponent(btnprevious)
                    .addComponent(btnlastpage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpanelEditbutton)
                    .addComponent(viewpanelDeletebutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EditPanel.setToolTipText("Student Details");
        EditPanel.setName("viewpanel"); // NOI18N
        EditPanel.setPreferredSize(new java.awt.Dimension(250, 200));

        jLabel16.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel16.setText("First Name");

        jLabel17.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel17.setText("Address");

        jLabel18.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel18.setText("Phone");

        jLabel19.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel19.setText("Gender");

        jLabel20.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel20.setText("Email");

        jLabel21.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel21.setText("DOB");

        EditCloseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EditCloseButton.setText("X");
        EditCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCloseButtonActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        addtitle2.setText("EDIT DATA");

        jLabel22.setFont(new java.awt.Font("Dolphin", 0, 18)); // NOI18N
        jLabel22.setText("Last Name");

        javax.swing.GroupLayout EditPanelLayout = new javax.swing.GroupLayout(EditPanel);
        EditPanel.setLayout(EditPanelLayout);
        EditPanelLayout.setHorizontalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPanelLayout.createSequentialGroup()
                        .addComponent(addtitle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditCloseButton))
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(23, 23, 23)
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditPanelLayout.createSequentialGroup()
                                .addComponent(updateBtn)
                                .addGap(0, 89, Short.MAX_VALUE))
                            .addGroup(EditPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditTextdob, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EditTextemail)))))
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditTextname))
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditTextgender)
                            .addComponent(EditTextphone)
                            .addComponent(EditTextlastname)
                            .addComponent(EditTextaddress))))
                .addContainerGap())
        );
        EditPanelLayout.setVerticalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPanelLayout.createSequentialGroup()
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditCloseButton)
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(addtitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(EditTextname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(EditTextlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(EditTextaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(EditTextphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(EditTextgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(EditTextemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(EditTextdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(EditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Student");

        addstd.setText("Add");
        addstd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstdActionPerformed(evt);
            }
        });
        jMenu4.add(addstd);

        viewstd.setText("View");
        viewstd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstdActionPerformed(evt);
            }
        });
        jMenu4.add(viewstd);

        editstd.setText("Edit");
        jMenu4.add(editstd);

        delstd.setText("Delete");
        jMenu4.add(delstd);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    ButtonGroup gender = new ButtonGroup();


    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new MainPage().setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    


    //---------------------------VIEW-PANEL CONTENTS AND EVENTS---------------------------
    public void DisplayInitialValues(){
        dbOperations.dbQueries dbQ = new dbOperations.dbQueries();
        rs = dbQ.viewStdInfo();
        try {
            if(rs.next()){
                getData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(viewpanel.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    public void getData(){
        try {
            this.studentId.setText(rs.getString("id"));
            this.lblname.setText(rs.getString("first_name")+" "+rs.getString("last_name"));
            this.lbladdress.setText(rs.getString("address"));
            this.lblphone.setText(rs.getString("phone"));
            this.lblgender.setText(rs.getString("gender"));
            this.lblemail.setText(rs.getString("email"));
            this.lbldob.setText(rs.getString("dob"));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"SQL Exception :"+ex.getMessage());
        }
                
    }
    
    

    private void viewstdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewstdActionPerformed

    private void addstdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstdActionPerformed
        // TODO add your handling code here:
        addpanel.setVisible(true);
    }//GEN-LAST:event_addstdActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

        if(StdId != 0){
            ArrayList data = new ArrayList();
            data.add(this.EditTextname.getText());
            data.add(this.EditTextlastname.getText());
            data.add(this.EditTextaddress.getText());
            data.add(this.EditTextphone.getText());

            //        if(this.radiomale.isSelected())
            //        data.add(this.radiomale.getText());
            //        else if(this.radiofemale.isSelected())
            //        data.add(this.radiofemale.getText());
            data.add(this.EditTextgender.getText());
            data.add(this.EditTextemail.getText());
            data.add(this.EditTextdob.getText());
            dbOperations.dbQueries dbQ = new dbOperations.dbQueries();
            dbQ.updateStdInfo(data,StdId);
            
            viewpanel.setVisible(false);
            toggleview.setSelected(false);
            EditPanel.setVisible(false);
            toggleedit.setSelected(false);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void EditCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCloseButtonActionPerformed
        EditPanel.setVisible(false);
        toggleedit.setSelected(false);
    }//GEN-LAST:event_EditCloseButtonActionPerformed

    public void getAllData(int id){
        
        EditPanel.setVisible(true);
        dbOperations.dbQueries dbQ = new dbOperations.dbQueries();
        rs = dbQ.VieweditStdInfo(id);
        try {
            if(rs.next()){
                this.EditTextname.setText(rs.getString("first_name"));
                this.EditTextlastname.setText(rs.getString("last_name"));
                this.EditTextaddress.setText(rs.getString("address"));
                this.EditTextphone.setText(rs.getString("phone"));
                this.EditTextgender.setText(rs.getString("gender"));
                this.EditTextemail.setText(rs.getString("email"));
                this.EditTextdob.setText(rs.getString("dob"));
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(viewpanel.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void viewpanelEditbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpanelEditbuttonActionPerformed
        StdId = Integer.parseInt(studentId.getText());
        getAllData(StdId);
        
    }//GEN-LAST:event_viewpanelEditbuttonActionPerformed

    private void viewpanelcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpanelcloseActionPerformed
        // TODO add your handling code here:
        viewpanel.setVisible(false);
        toggleview.setSelected(false);
    }//GEN-LAST:event_viewpanelcloseActionPerformed

    private void btnlastpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastpageActionPerformed
        // TODO add your handling code here:
        try {
            if(rs.last()){
                getData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(viewpanel.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnlastpageActionPerformed

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
        // TODO add your handling code here:
        try {
            if(rs.previous()){
                getData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(viewpanel.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnpreviousActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        try {
            if(rs.next()){
                getData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(viewpanel.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnfirstpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstpageActionPerformed
        // TODO add your handling code here:
        try {
            if(rs.first()){
                getData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(viewpanel.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnfirstpageActionPerformed

    private void toggleaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleaddActionPerformed
        // TODO add your handling code here:
        if(toggleadd.isSelected()){
            addpanel.setVisible(true);
        }
        else if(!toggleadd.isSelected())
        addpanel.setVisible(false);
    }//GEN-LAST:event_toggleaddActionPerformed

    private void toggleeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleeditActionPerformed
        // TODO add your handling code here:
        if(toggleedit.isSelected()){
            if(toggleview.isSelected() == false){
                viewpanel.setVisible(true);
                DisplayInitialValues();
                toggleview.setSelected(true);
            }
            viewpanelEditbutton.setVisible(true);
            viewpanelDeletebutton.setVisible(true);
        }
        else{
            viewpanelEditbutton.setVisible(false);            
            viewpanelDeletebutton.setVisible(false);
            EditPanel.setVisible(false);
        }

    }//GEN-LAST:event_toggleeditActionPerformed

    private void toggleviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleviewActionPerformed
        // TODO add your handling code here:
        if(toggleview.isSelected()){
            viewpanel.setVisible(true);
            DisplayInitialValues();
        }
        else{
            viewpanel.setVisible(false);
        }
        viewpanelEditbutton.setVisible(false);
        viewpanelDeletebutton.setVisible(false);
    }//GEN-LAST:event_toggleviewActionPerformed

    //---------------------------ADDPANEL CONTENTS AND EVENTS---------------------------
    private void addpanelcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpanelcloseActionPerformed
        // TODO add your handling code here:
        addpanel.setVisible(false);
        toggleadd.setSelected(false);
    }//GEN-LAST:event_addpanelcloseActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        ArrayList data = new ArrayList();
        data.add(this.txtfirstname.getText());
        data.add(this.txtlastname.getText());
        data.add(this.txtaddress.getText());
        data.add(this.txtphone.getText());

        if(this.radiomale.isSelected())
        data.add(this.radiomale.getText());
        else if(this.radiofemale.isSelected())
        data.add(this.radiofemale.getText());

        data.add(this.txtemail.getText());
        data.add(this.txtdob.getText());

        dbOperations.dbQueries dbQ = new dbOperations.dbQueries();
        dbQ.addStdInfo(data);
    }//GEN-LAST:event_btnsaveActionPerformed

    private void radiofemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiofemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiofemaleActionPerformed

    private void radiomaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiomaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiomaleActionPerformed

    private void viewpanelDeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpanelDeletebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewpanelDeletebuttonActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        // TODO add your handling code here:
        DisplayInitialValues();
        new ViewAll().setVisible(true);
    }//GEN-LAST:event_btnViewAllActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditCloseButton;
    private javax.swing.JPanel EditPanel;
    private javax.swing.JTextField EditTextaddress;
    private javax.swing.JTextField EditTextdob;
    private javax.swing.JTextField EditTextemail;
    private javax.swing.JTextField EditTextgender;
    private javax.swing.JTextField EditTextlastname;
    private javax.swing.JTextField EditTextname;
    private javax.swing.JTextField EditTextphone;
    private javax.swing.JPanel addpanel;
    private javax.swing.JButton addpanelclose;
    private javax.swing.JMenuItem addstd;
    private javax.swing.JLabel addtitle;
    private javax.swing.JLabel addtitle1;
    private javax.swing.JLabel addtitle2;
    private javax.swing.JToggleButton btnViewAll;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnfirstpage;
    private javax.swing.JButton btnlastpage;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprevious;
    private javax.swing.JButton btnsave;
    private javax.swing.JMenuItem delstd;
    private javax.swing.JMenuItem editstd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphone;
    private javax.swing.JRadioButton radiofemale;
    private javax.swing.JRadioButton radiomale;
    private javax.swing.JLabel studentId;
    private javax.swing.JToggleButton toggleadd;
    private javax.swing.JToggleButton toggleedit;
    private javax.swing.JToggleButton toggleview;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel viewpanel;
    private javax.swing.JButton viewpanelDeletebutton;
    private javax.swing.JButton viewpanelEditbutton;
    private javax.swing.JButton viewpanelclose;
    private javax.swing.JMenuItem viewstd;
    // End of variables declaration//GEN-END:variables
}
